// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, audioEnd, carminaAudio, composerHandler, composerIndex, composerPortraits, newAudio, soundToggle, updateTimerVisibility, show, adjust, updateComposer, startMedia, stopMedia, toggle, reset, blink, count, run, resize;
start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
audioEnd = null;
carminaAudio = null;
composerHandler = null;
composerIndex = 0;
composerPortraits = [
  {
    name: 'Johann Sebastian Bach',
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Johann_Sebastian_Bach.jpg'
  },
  {
    name: 'Ludwig van Beethoven',
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Beethoven.jpg'
  },
  {
    name: 'Wolfgang Amadeus Mozart',
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Wolfgang-amadeus-mozart_1.jpg'
  },
  {
    name: 'Frédéric Chopin',
    url: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Chopin%2C_by_Wodzinska.JPG'
  },
  {
    name: 'Pyotr Ilyich Tchaikovsky',
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Piotr_Tchaikovsky_by_Ku%C4%87i%C5%9B_%281879%29.jpg'
  },
  {
    name: 'Claude Debussy',
    url: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Claude_Debussy_atelier_Nadar.jpg'
  },
  {
    name: 'Giuseppe Verdi',
    url: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Giuseppe_Verdi.jpg'
  },
  {
    name: 'Antonio Vivaldi',
    url: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Antonio_Vivaldi.jpg'
  },
  {
    name: 'Johannes Brahms',
    url: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/JohannesBrahms.jpg'
  },
  {
    name: 'Franz Schubert',
    url: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Franz_Schubert_by_Wilhelm_August_Riezler.jpg'
  }
];
newAudio = function(file, loop){
  var x$, node;
  loop == null && (loop = false);
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = loop;
  x$.load();
  document.body.appendChild(node);
  return node;
};
soundToggle = function(des, state){
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};
updateTimerVisibility = function(){
  var tm;
  tm = $('#timer');
  if (isRun) {
    return tm.addClass('timer-hidden');
  } else {
    return tm.removeClass('timer-hidden');
  }
};
show = function(){
  isShow = !isShow;
  return $('.fbtn').css('opacity', isShow ? '1.0' : '0.1');
};
adjust = function(it, v){
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
  }
  if (delay <= 0) {
    delay = 0;
  }
  $('#timer').text(delay);
  return resize();
};
updateComposer = function(){
  var data, img, caption;
  data = composerPortraits[composerIndex];
  img = $('#composer-photo');
  caption = $('#composer-name');
  img.attr('src', data.url);
  img.attr('alt', data.name + " portrait");
  caption.text(data.name);
  return composerIndex = (composerIndex + 1) % composerPortraits.length;
};
startMedia = function(){
  updateComposer();
  if (composerHandler) {
    clearInterval(composerHandler);
  }
  composerHandler = setInterval(function(){
    return updateComposer();
  }, 8000);
  if (carminaAudio) {
    return soundToggle(carminaAudio, true);
  }
};
stopMedia = function(){
  if (composerHandler) {
    clearInterval(composerHandler);
    composerHandler = null;
  }
  if (carminaAudio) {
    return soundToggle(carminaAudio, false);
  }
};
toggle = function(){
  isRun = !isRun;
  updateTimerVisibility();
  $('#toggle').text(isRun ? "STOP" : "RUN");
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    soundToggle(audioEnd, false);
    soundToggle(audioRemind, false);
    stopMedia();
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    startMedia();
    return run();
  }
};
reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  soundToggle(audioRemind, false);
  soundToggle(audioEnd, false);
  stopMedia();
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  $('#timer').text(delay);
  $('#timer').css('color', '#fff');
  return resize();
};
blink = function(){
  isBlink = true;
  isLight = !isLight;
  return $('#timer').css('color', isLight ? '#fff' : '#f00');
};
count = function(){
  var tm, diff;
  tm = $('#timer');
  diff = start.getTime() - new Date().getTime() + delay + latency;
  if (diff > 60000) {
    isWarned = false;
  }
  if (diff < 60000 && !isWarned) {
    isWarned = true;
    soundToggle(audioRemind, true);
  }
  if (diff < 55000) {
    soundToggle(audioRemind, false);
  }
  if (diff < 0 && !isBlink) {
    soundToggle(audioEnd, true);
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  tm.text(diff + "");
  return resize();
};
run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    return handler = setInterval(function(){
      return count();
    }, 100);
  }
};
resize = function(){
  var tm, w, h, len;
  tm = $('#timer');
  w = tm.width();
  h = $(window).height();
  len = tm.text().length;
  len >= 3 || (len = 3);
  tm.css('font-size', 1.5 * w / len + "px");
  return tm.css('line-height', h + "px");
};
window.onload = function(){
  $('#timer').text(delay);
  resize();
  audioRemind = newAudio('audio/smb_warning.mp3');
  audioEnd = newAudio('audio/smb_mariodie.mp3');
  carminaAudio = newAudio('https://upload.wikimedia.org/wikipedia/commons/4/4a/Carl_Orff_-_O_Fortuna%2C_Carmina_Burana.ogg', true);
  return $('#composer-name').text('Composer spotlight');
};
window.onresize = function(){
  return resize();
};
